# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: node:10.15.3
image: node:current-alpine

pipelines:
  branches: # Automated triggers on commits to branches
   master: # -- When committing to master branch
    - step:
        name: Build
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install --save-dev  --unsafe-perm node-sass
          - npm run ng build -- --prod --output-path=dist
          - ls -ltr dist
          - pipe: atlassian/ftp-deploy:0.3.3
            variables:
                USER: $INVITATION_USER
                PASSWORD: $INVITATION_PASSWORD
                SERVER: $DEPLOY_SERVER
                REMOTE_PATH: '/'
                LOCAL_PATH: 'dist' # Optional
                # DEBUG: '' # Optional